### ISSUE TITLE
Error on evaluating expressions on console

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-plunit-server#10]
Example: 

```
ム X = 4. 
ERROR: writeBinding/1: Undefined procedure: compound_name_arguments/3
Exception: (8) compound_name_arguments('X'=4, =, [_G1004, _G1007]) ? EOF: exit
```

This happens always, regardless of the final dot presence.

**Comment by flbulgarelli** [comment]
Could we fix this and add an integration test?

**Comment by flbulgarelli** [comment]
BTW, this may see a SWI prolog version issue. In which SWI prolog version was `compound_name_arguments` introduced?

**Comment by gcrespi** [comment]
Yes, you are right it was introduced in the 7.XX version acording to this link: http://www.swi-prolog.org/pldoc/doc_for?object=compound_name_arguments/3 (it's tagged SWI7), can we update prolog production version?, and put it in a git module so we can update it easier next time?.

**Comment by flbulgarelli** [comment]
Hmm, it is not that easy because we need to recompile prolog within Heroku. I is a time consuming, manual task. 

If there is no other option I will do that, but could we try to use another predicate?

**Comment by gcrespi** [comment]
This looks like a winner: http://www.swi-prolog.org/pldoc/man?predicate=%3D../2
I will research more this afternoon, and try to use it

**Comment by flbulgarelli** [comment]
Awesome!

**Comment by flbulgarelli** [comment]
Yeah, @PalumboN loves `=..`
